- op: replace
  path: /metadata/name
  value: prometheus-config-reloader
- op: replace
  path: /spec/componentName
  value: prometheus-config-reloader
- op: replace
  path: /spec/source/git/url
  value: https://github.com/stolostron/prometheus-operator
- op: replace
  path: /spec/source/git/dockerfileUrl
  value: "cmd/prometheus-config-reloader/Dockerfile"