apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
  - ../../../../base

patches:
  - path: multicluster-global-hub-operator.yaml
    target:
      kind: Component
