---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: rpa-stage-mce-27
  labels:
    release.appstudio.openshift.io/auto-release: 'false'
    pp.engineering.redhat.com/business-unit: <bu-name> #hybrid-cloud-experience ??
spec:
  applications:
    - release-mce-27
  origin: crt-redhat-acm-tenant
  policy: always-pass-policy
  data:
    mapping:
      components: 
        - name: addon-manager-mce-27
          repository: quay.io/stolostron/addon-manager-rhel9
        - name: backplane-must-gather-mce-27
          repository: quay.io/stolostron/must-gather-rhel9
        - name: backplane-operator-mce-27
          repository: quay.io/stolostron/backplane-rhel9-operator
        - name: cluster-api-provider-kubevirt-mce-27
          repository: quay.io/stolostron/cluster-api-provider-kubevirt-rhel9
        - name: cluster-curator-controller-mce-27
          repository: quay.io/stolostron/cluster-curator-controller-rhel9
        - name: cluster-image-set-controller-mce-27
          repository: quay.io/stolostron/cluster-image-set-controller-rhel9
        - name: cluster-proxy-addon-mce-27
          repository: quay.io/stolostron/cluster-proxy-addon-rhel9
        - name: cluster-proxy-mce-27
          repository: quay.io/stolostron/cluster-proxy-rhel9
        - name: clusterclaims-controller-mce-27
          repository: quay.io/stolostron/clusterclaims-controller-rhel9
        - name: clusterlifecycle-state-metrics-mce-27
          repository: quay.io/stolostron/clusterlifecycle-state-metrics-rhel9
        - name: console-mce-mce-27
          repository: quay.io/stolostron/console-mce-rhel9
        - name: discovery-operator-mce-27
          repository: quay.io/stolostron/discovery-rhel9
        - name: hive-mce-27
          repository: quay.io/stolostron/hive-rhel9
        - name: hypershift-addon-rhel9-operator
          repository: quay.io/stolostron/hypershift-addon-operator-mce-27
        - name: hypershift-release-mce-27
          repository: quay.io/stolostron/hypershift-rhel9-operator
        - name: image-based-install-operator-mce-27
          repository: quay.io/stolostron/image-27d-install-rhel9
        - name: kube-rbac-proxy-mce-27
          repository: quay.io/stolostron/kube-rbac-proxy-mce-rhel9
        - name: managed-serviceaccount-mce-27
          repository: quay.io/stolostron/managed-serviceaccount-rhel9
        - name: managedcluster-import-controller-addon-mce-27
          repository: quay.io/stolostron/managedcluster-import-controller-rhel9
        - name: multicloud-manager-mce-27
          repository: quay.io/stolostron/multicloud-manager-rhel9
        - name: placement-mce-27
          repository: quay.io/stolostron/placement-rhel9
        - name: provider-credential-controller-mce-27
          repository: quay.io/stolostron/provider-credential-controller-rhel9
        - name: registration-mce-27
          repository: quay.io/stolostron/registration-rhel9
        - name: registration-operator-mce-27
          repository: quay.io/stolostron/registration-operator-rhel9
        - name: work-mce-27
          repository: quay.io/stolostron/work-rhel9
      defaults:
        tags:
          - "2.7.3-{{  incrementer  }}"
          - "2.7.3-{{ timestamp }}"
          - "2.7.3-{{ git_short_sha }}"
  pipeline:
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: "https://github.com/konflux-ci/release-service-catalog.git"
        - name: revision
          value: stage
        - name: pathInRepo
          value: "pipelines/rh-advisories/rh-advisories.yaml"