---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: dev-publish-mce
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
spec:
  applications:
    - release-mce-27
  data:
    mapping:
      components:
        - name: cluster-image-set-controller-mce-27
          repository: quay.io/acm-p/cluster-image-set-controller-mce-27
          tags: #OPTIONS == 
            - latest
            - "{{ git_sha }}"
            - "{{ git_short_sha }}"
            - "{{ digest_sha }}"
            - "{{ labels.konflux.additional-tags }}-{{ incrementer }}"
        - name: hive-mce-27
          repository: quay.io/acm-p/hive-mce-27
          tags: [latest]
        - name: image-based-install-operator-mce-27
          repository: quay.io/acm-p/image-based-install-operator-mce-27
          tags: [latest]
        - name: kube-rbac-proxy-mce-27
          repository: quay.io/acm-p/kube-rbac-proxy-mce-27
          tags: [latest]
        - name: clusterlifecycle-state-metrics-mce-27
          repository: quay.io/acm-p/clusterlifecycle-state-metrics-mce-27
          tags: [latest]
        - name: console-mce-mce-27
          repository: quay.io/acm-p/console-mce-mce-27
          tags: [latest]
        - name: clusterclaims-controller-mce-27
          repository: quay.io/acm-p/clusterclaims-controller-mce-27
          tags: [latest]
        - name: provider-credential-controller-mce-27
          repository: quay.io/acm-p/provider-credential-controller-mce-27
          tags: [latest]
        - name: cluster-curator-controller-mce-27
          repository: quay.io/acm-p/cluster-curator-controller-mce-27
          tags: [latest]
        - name: hypershift-release-mce-27
          repository: quay.io/acm-p/hypershift-release-mce-27
          tags: [latest]
        - name: cluster-proxy-mce-27
          repository: quay.io/acm-p/cluster-proxy-mce-27
          tags: [latest]
        - name: discovery-operator-mce-27
          repository: quay.io/acm-p/discovery-operator-mce-27
          tags: [latest]
        - name: backplane-operator-mce-27
          repository: quay.io/acm-p/backplane-operator-mce-27
          tags: [latest]
  origin: mce-base
tenantPipeline:
  pipelineRef: 
    resolver: git
    params:
      - name: url
        value: "https://github.com/scoheb/release-service-catalog"
      - name: revision
        value: tenant-release-pipelines
      - name: pathInRepo
        value: "pipelines/tenant-push-to-external-registry/tenant-push-to-external-registry.yaml"
  serviceAccountName: appstudio-pipeline
policy: default