apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
  - application.yaml
  - ./addon-manager
  - ./backplane-must-gather
  - ./backplane-operator
  - ./cluster-api-provider-agent
  - ./cluster-api-provider-kubevirt
  - ./cluster-curator-controller
  - ./cluster-image-set-controller
  - ./cluster-proxy 
  - ./cluster-proxy-addon 
  - ./clusterclaims-controller 
  - ./clusterlifecycle-state-metrics
  - ./console-mce
  - ./discovery-operator
  - ./hive 
  - ./hypershift-addon-operator 
  - ./hypershift-release
  - ./image-based-install-operator
  - ./kube-rbac-proxy 
  - ./managed-serviceaccount 
  - ./managedcluster-import-controller-addon
  - ./multicloud-manager
  - ./placement
# - ./postgresql-12-centos7
  - ./provider-credential-controller 
  - ./registration
  - ./registration-operator
  - ./work 

# Assisted Installer will be self-managed
# Discovery repos aren't published
# Postgres still needs work
# All other repos are deprecated or managed elsewhere
  # - ./addon-framework
  # - ./apiserver-network-proxy
  # - ./assisted-image-service
  # - ./assisted-installer
  # - ./assisted-installer-agent
  # - ./assisted-installer-controller
  # - ./assisted-service
  # - ./aws-encryption-provider
  # - ./cluster-api
  # - ./cluster-api-aws-controller
  # - ./cluster-api-provider-azure
  # - ./discovery-operator-tests
  # - ./discovery-testserver