apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -globalhub-1-3
resources:
  - ../global-hub-base

patches:
  - target:
      kind: Application
    path: application-patch.yaml
  - target:
      kind: Component
    path: component-patch.yaml
  - target:
      kind: Component
      name: glo-grafana
    path: glo-grafana-branch-patch.yaml