- op: replace
  path: /metadata/name
  value: cluster-api-webhook-config
- op: replace
  path: /spec/componentName
  value: cluster-api-webhook-config
- op: replace
  path: /spec/source/git/url
  value: https://github.com/stolostron/cluster-api-installer
- op: replace
  path: /spec/source/git/dockerfileUrl
  value: "mce-capi-webhook-config/Dockerfile"