---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: rpa-prod-mce-28
  labels:
    release.appstudio.openshift.io/auto-release: 'false'
    pp.engineering.redhat.com/business-unit: <bu-name> #hybrid-cloud-experience ??
spec:
  applications:
    - release-mce-28
  data:
    releaseNotes:
      product_id: <product ID> # ??
      product_name: multicluster engine for Kubernetes
      product_version: 2.8.0
    mapping:
      components: 
        - name: addon-manager-mce-28 
          repository: registry.redhat.io/multicluster-engine/addon-manager-rhel9, 
        - name: backplane-must-gather-mce-28 
          repository: registry.redhat.io/multicluster-engine/must-gather-rhel9, 
        - name: backplane-operator-mce-28 
          repository: registry.redhat.io/multicluster-engine/backplane-rhel9-operator, 
        - name: cluster-api-provider-kubevirt-mce-28 
          repository: registry.redhat.io/multicluster-engine/cluster-api-provider-kubevirt-rhel9, 
        - name: cluster-curator-controller-mce-28 
          repository: registry.redhat.io/multicluster-engine/cluster-curator-controller-rhel9, 
        - name: cluster-image-set-controller-mce-28 
          repository: registry.redhat.io/multicluster-engine/cluster-image-set-controller-rhel9, 
        - name: cluster-proxy-addon-mce-28 
          repository: registry.redhat.io/multicluster-engine/cluster-proxy-addon-rhel9, 
        - name: cluster-proxy-mce-28 
          repository: registry.redhat.io/multicluster-engine/cluster-proxy-rhel9, 
        - name: clusterclaims-controller-mce-28 
          repository: registry.redhat.io/multicluster-engine/clusterclaims-controller-rhel9, 
        - name: clusterlifecycle-state-metrics-mce-28 
          repository: registry.redhat.io/multicluster-engine/clusterlifecycle-state-metrics-rhel9, 
        - name: console-mce-mce-28 
          repository: registry.redhat.io/multicluster-engine/console-mce-rhel9, 
        - name: discovery-operator-mce-28 
          repository: registry.redhat.io/multicluster-engine/discovery-rhel9, 
        - name: hive-mce-28 
          repository: registry.redhat.io/multicluster-engine/hive-rhel9, 
        - name: hypershift-addon-operator-mce-28 
          repository: registry.redhat.io/multicluster-engine/hypershift-addon-rhel9-operator, 
        - name: hypershift-release-mce-28 #FIX THIS
          repository: quay.io/acm-p/hypershift-release-mce-28 
        - name: hypershift-cli-mce-28, 
          repository: registry.redhat.io/multicluster-engine/hypershift-cli-rhel9, 
        - name: hypershift-operator-mce-28 
          repository: registry.redhat.io/multicluster-engine/hypershift-rhel9-operator, 
        - name: image-based-install-operator-mce-28 
          repository: registry.redhat.io/multicluster-engine/image-based-install-rhel9, 
        - name: kube-rbac-proxy-mce-28 
          repository: registry.redhat.io/multicluster-engine/kube-rbac-proxy-mce-rhel9, 
        - name: managed-serviceaccount-mce-28 
          repository: registry.redhat.io/multicluster-engine/managed-serviceaccount-rhel9, 
        - name: managedcluster-import-controller-addon-mce-28 
          repository: registry.redhat.io/multicluster-engine/managedcluster-import-controller-rhel9, 
        - name: multicloud-manager-mce-28 
          repository: registry.redhat.io/multicluster-engine/multicloud-manager-rhel9, 
        - name: placement-mce-28 
          repository: registry.redhat.io/multicluster-engine/placement-rhel9, 
        - name: provider-credential-controller-mce-28 
          repository: registry.redhat.io/multicluster-engine/provider-credential-controller-rhel9, 
        - name: registration-mce-28 
          repository: registry.redhat.io/multicluster-engine/registration-rhel9, 
        - name: registration-operator-mce-28 
          repository: registry.redhat.io/multicluster-engine/registration-operator-rhel9@sha256, 
        - name: work-mce-28 
          repository: registry.redhat.io/multicluster-engine/work-rhel9, 
      defaults:
        tags:
          - "2.8.0-{{  incrementer  }}"
          - "2.8.0-{{ timestamp }}"
          - "2.8.0-{{ git_short_sha }}"
#    pushSourceContainer: true
#  pyxis:
#    secret: pyxis-production-secret
#    server: production
# environment: <sre-production>
  origin: mce-base
  pipeline:
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: "https://github.com/konflux-ci/release-service-catalog.git"
        - name: revision
          value: production
        - name: pathInRepo
          value: "pipelines/rh-advisories/rh-advisories.yaml"
  policy: registry-standard #Need a policy to publish release
  serviceAccount: release-registry-prod 