apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: prod-publish-catalog-418-glo-142-release
  namespace: acm-multicluster-glo-tenant
  labels:
    release.appstudio.openshift.io/author: "chuyang"
spec:
  data:
    releaseNotes:
      type: RHBA
  releasePlan: catalog-418-publish-prod-globalhub-1-4
  snapshot: release-catalog-418-globalhub-1-4-l6kmd
