apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
  - ../../../../base

patches:
  - path: multicluster-operator-subscription.yaml
    target:
      kind: Component
