apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -acm-214
resources:
  - ../acm-operator-bundle-base
  - releaseplan-dev.yaml
  - rpa-dev.yaml
  # - releaseplan-prod.yaml -- NEED TO CREATE THESE
  # - rpa-prod.yaml
  # - releaseplan-stage.yaml
  # - rpa-stage.yaml

patches:
  - target:
      kind: Application
    path: application-patch.yaml
  - target:
      kind: Component
    path: component-patch.yaml
