apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
 labels:
   release.appstudio.openshift.io/auto-release: 'false'
   release.appstudio.openshift.io/standing-attribution: 'true'
   release.appstudio.openshift.io/releasePlanAdmission: 'rpa-stage-acm-214'
 name: stage-publish
 namespace: crt-redhat-acm-tenant #assisted installer workspace
spec:
 application: release-acm-214 #Application we're getting components from
 data:
  releaseNotes:
    synopsis: Advanced Cluster Management for Kubernetes 2.14 for RHEL 9
    topic: Advanced Cluster Management v2.14
    description: Advanced Cluster Management for Kubernetes 2.14
    solution: Advanced Cluster Management for Kubernetes v2.14 images
 target: rhtap-releng-tenant
