apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
 labels:
   release.appstudio.openshift.io/auto-release: 'true' 
 name: rpa-dev
 namespace: crt-redhat-acm-tenant
spec:
  applications: 
    - release-acm-214
  origin: crt-redhat-acm-tenant
  policy: always-pass-policy
  data:
    mapping:
      components:
        - name: insights-client-acm-214
          repository: quay.io/acm-d/insights-client-rhel9
        - name: klusterlet-addon-controller-acm-214
          repository: quay.io/acm-d/klusterlet-addon-controller-rhel9
        - name: acm-cli-acm-214
          repository: quay.io/acm-d/acm-cli-rhel9
        - name: multicluster-operators-channel-acm-214
          repository: quay.io/acm-d/multicluster-operators-channel-rhel9
        - name: must-gather-acm-214
          repository: quay.io/acm-d/must-gather-rhel9
        - name: governance-policy-addon-controller-acm-214
          repository: quay.io/acm-d/acm-governance-policy-addon-controller-rhel9
        - name: search-indexer-acm-214
          repository: quay.io/acm-d/acm-search-indexer-rhel9
        - name: governance-policy-framework-addon-acm-214
          repository: quay.io/acm-d/acm-governance-policy-framework-addon-rhel9
        - name: observatorium-acm-214
          repository: quay.io/acm-d/observatorium-rhel9
        - name: multiclusterhub-operator-acm-214
          repository: quay.io/acm-d/multiclusterhub-rhel9
        - name: metrics-collector-acm-214
          repository: quay.io/acm-d/metrics-collector-rhel9
        - name: grafana-acm-214
          repository: quay.io/acm-d/acm-grafana-rhel9
        - name: prometheus-operator-acm-214
          repository: quay.io/acm-d/prometheus-rhel9
        - name: multicluster-operators-subscription-acm-214
          repository: quay.io/acm-d/multicluster-operators-subscription-rhel9
        - name: cluster-permission-acm-214
          repository: quay.io/acm-d/acm-cluster-permission-rhel9
        - name: submariner-addon-acm-214
          repository: quay.io/acm-d/submariner-addon-rhel9
        - name: thanos-acm-214
          repository: quay.io/acm-d/thanos-rhel9
        - name: node-exporter-acm-214
          repository: quay.io/acm-d/node-exporter-rhel9
        - name: multicluster-operators-application-acm-214
          repository: quay.io/acm-d/multicluster-operators-application-rhel9
        - name: kube-state-metrics-acm-214
          repository: quay.io/acm-d/kube-state-metrics-rhel9
        - name: search-collector-acm-214
          repository: quay.io/acm-d/search-collector-rhel9
        - name: multicluster-observability-addon-acm-214
          repository: quay.io/acm-d/multicluster-observability-addon-rhel9
        - name: multicloud-integrations-acm-214
          repository: quay.io/acm-d/multicloud-integrations-rhel9
        - name: thanos-receive-controller-acm-214
          repository: quay.io/acm-d/thanos-receive-controller-rhel9
        - name: memcached-exporter-acm-214
          repository: quay.io/acm-d/memcached-exporter-rhel9
        - name: volsync-addon-controller-acm-214
          repository: quay.io/acm-d/acm-volsync-addon-controller-rhel9
        - name: search-v2-api-acm-214
          repository: quay.io/acm-d/acm-search-v2-api-rhel9
        - name: siteconfig-acm-214
          repository: quay.io/acm-d/acm-siteconfig-rhel9
        - name: prometheus-acm-214
          repository: quay.io/acm-d/prometheus-rhel9
        - name: config-policy-controller-acm-214
          repository: quay.io/acm-d/config-policy-controller-rhel9
        - name: kube-rbac-proxy-acm-214
          repository: quay.io/acm-d/kube-rbac-proxy-rhel9
        - name: cert-policy-controller-acm-214
          repository: quay.io/acm-d/cert-policy-controller-rhel9
        - name: prometheus-alertmanager-acm-214
          repository: quay.io/acm-d/prometheus-alertmanager-rhel9
        - name: rbac-query-proxy-acm-214
          repository: quay.io/acm-d/rbac-query-proxy-rhel9
        - name: prometheus-config-reloader-acm-214
          repository: quay.io/acm-d/acm-prometheus-config-reloader-rhel9
        - name: governance-policy-propagator-acm-214
          repository: quay.io/acm-d/governance-policy-propagator-rhel9
        - name: observatorium-operator-acm-214
          repository: quay.io/acm-d/observatorium-operator-rhel9
        - name: search-v2-operator-acm-214
          repository: quay.io/acm-d/acm-search-v2-rhel9
        - name: endpoint-monitoring-operator-acm-214
          repository: quay.io/acm-d/endpoint-monitoring-rhel9-operator
        - name: insights-metrics-acm-214
          repository: quay.io/acm-d/insights-metrics-rhel9
        - name: console-acm-214
          repository: quay.io/acm-d/console-rhel9
        - name: grafana-dashboard-loader-acm-214
          repository: quay.io/acm-d/grafana-dashboard-loader-rhel9
        - name: multicluster-observability-operator-acm-214
          repository: quay.io/acm-d/multicluster-observability-rhel9-operator
        - name: cluster-backup-operator-acm-214
          repository: quay.io/acm-d/cluster-backup-rhel9-operator
      defaults:
        tags:
          - "2.14.0-{{  incrementer  }}"
          - "2.14.0-{{ timestamp }}"
          - "2.14.0-{{ git_short_sha }}"
  pipeline:
    pipelineRef: 
      resolver: git
      params:
        - name: url
          value: "https://github.com/konflux-ci/release-service-catalog.git"
        - name: revision
          value: development
        - name: pathInRepo
          value: "pipelines/managed/push-to-external-registry/push-to-external-registry.yaml"
    timeouts:
      pipeline: "4h0m0s"
