apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: prod-publish-volsync-fbc-4-14-v0-13-0
  namespace: volsync-tenant
  labels:
    release.appstudio.openshift.io/author: "tflower"
spec:
  snapshot: "volsync-fbc-4-14-q8crm"
  releasePlan: volsync-fbc-release-plan-prod-4-14
