- op: replace
  path: /metadata/name
  value: bundle-release
- op: replace
  path: /spec/description
  value: "Bundle Build for MCE 2.7"
- op: replace
  path: /spec/displayName
  value: "MCE Bundle 2.7"