apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -mce-27
resources:
  - ../mce-operator-bundle-base

patches:
  - target:
      kind: Application
    path: application-patch.yaml
  - target:
      kind: Component
    path: component-patch.yaml